sudo: false
dist: xenial
language: c
matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - T=linux-clang-asan
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2 -fsanitize=address -fno-sanitize-recover=all'
        - TESTFLAGS='-T leaky'

    - os: linux
      compiler: clang
      env:
        - T=linux-clang-ubsan
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2 -fsanitize=undefined,unsigned-integer-overflow -fno-sanitize-recover=all'

    - os: linux
      compiler: gcc
      env:
        - T=linux-gcc-asan
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2 -fsanitize=address -fno-sanitize-recover=all'
        - TESTFLAGS='-T leaky'

    - os: linux
      compiler: gcc
      env:
        - T=linux-gcc-ubsan
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2 -fsanitize=undefined -fno-sanitize-recover=all'

    - os: linux
      compiler: musl-gcc
      env:
        - T=linux-musl
        - CFLAGS=-Werror
        - TESTFLAGS='-T tilde'
      addons:
        apt:
          packages:
            - musl-tools

    - os: linux
      compiler: clang
      env:
        - T=linux-valgrind
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2'
        - EXEC=valgrind
        - TESTFLAGS='-T leaky'
        - VALGRIND_OPTS='--quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all'
      addons:
        apt:
          packages:
            - valgrind

    - os: osx
      compiler: clang
      env:
        - T=macos-clang
        - CFLAGS=-Werror
        - CPPFLAGS=-D_FORTIFY_SOURCE=2
        - DEBUG='-g -O2'

script:
  - |
    (
    set -ex
    case $T in
    *)
      ./configure || true
      cat config.log
      make test
      # Ensure assertions are free from side effects.
      env CPPFLAGS="${CPPFLAGS} -DNDEBUG" ./configure || true
      cat config.log
      make test
      ;;
    esac
    )
