sudo: false
dist: trusty
language: c
matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - DEBUG='-g -fsanitize=undefined -fno-sanitize-recover=undefined'
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=default
        - CFLAGS=-Werror
    - os: linux
      compiler: musl-gcc
      env:
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - TESTFLAGS='-s tilde\ expansion'
      addons:
        apt:
          packages:
            - musl-tools
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - TESTFLAGS='-s too\ long'
script:
  - |
    (
    set -ex
    case $BUILD_TYPE in
    default)
      ./configure || true
      cat config.log
      make test
      ;;
    esac
    )
