sudo: false
dist: trusty
language: c
matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - T=linux-clang-ubsan
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - DEBUG='-g -fsanitize=undefined -fno-sanitize-recover=undefined'

    - os: linux
      compiler: gcc
      env:
        - T=linux-gcc
        - BUILD_TYPE=default
        - CFLAGS=-Werror

    - os: linux
      compiler: gcc-8
      env:
        - T=linux-gcc-ubsan
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - DEBUG='-g -fsanitize=undefined -fno-sanitize-recover=undefined  -fuse-ld=gold'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8

    - os: linux
      compiler: musl-gcc
      env:
        - T=linux-musl
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - TESTFLAGS='-i tilde\ expansion'
      addons:
        apt:
          packages:
            - musl-tools

    - os: osx
      compiler: clang
      env:
        - T=macos-clang
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - TESTFLAGS='-i too\ long'

    - os: linux
      compiler: clang
      env:
        - T=linux-valgrind
        - BUILD_TYPE=default
        - CFLAGS=-Werror
        - DEBUG-g
        - TESTFLAGS='-e valgrind -i conf.sh'
        - VALGRIND_OPTS='--quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all'
      addons:
        apt:
          packages:
            - valgrind

script:
  - |
    (
    set -ex
    case $BUILD_TYPE in
    default)
      ./configure || true
      cat config.log
      make test
      # Ensure assertions are free from side effects.
      env CPPFLAGS=-DNDEBUG ./configure || true
      cat config.log
      make test
      ;;
    esac
    )
