sudo: false
dist: bionic
language: c

env:
  global:
    - CFLAGS="-Werror -Wshadow"
    - CPPFLAGS=-D_FORTIFY_SOURCE=2
    - DEBUG="-g -O2"

matrix:
  include:
    - arch: amd64
      os: linux
      compiler: clang
      env:
        - T=amd64-linux-clang-asan
        - DEBUG="${DEBUG} -fsanitize=address -fno-sanitize-recover=all"
        - TESTFLAGS='-T leaky'

    - arch: amd64
      os: linux
      compiler: clang
      env:
        - T=amd64-linux-clang-ubsan
        - DEBUG="${DEBUG} -fsanitize=undefined,unsigned-integer-overflow -fno-sanitize-recover=all"

    - arch: amd64
      os: linux
      compiler: gcc
      env:
        - T=amd64-linux-gcc-asan
        - CFLAGS="${CFLAGS} -Wformat-signedness"
        - DEBUG="${DEBUG} -fsanitize=address -fno-sanitize-recover=all"
        - TESTFLAGS="-T leaky"

    - arch: amd64
      os: linux
      compiler: gcc
      env:
        - T=amd64-linux-gcc-ubsan
        - CFLAGS="${CFLAGS} -Wformat-signedness"
        - DEBUG="${DEBUG} -fsanitize=undefined -fno-sanitize-recover=all"

    - arch: amd64
      os: linux
      compiler: musl-gcc
      env:
        - T=amd64-linux-musl
        - CFLAGS="${CFLAGS} -Wformat-signedness"
        - TESTFLAGS="-T tilde"
      addons:
        apt:
          packages:
            - musl-tools

    - arch: amd64
      os: linux
      compiler: clang
      env:
        - T=amd64-linux-valgrind
        - EXEC=valgrind
        - TESTFLAGS="-T leaky"
        - VALGRIND_OPTS="--quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all"
      addons:
        apt:
          packages:
            - valgrind

    - arch: amd64
      os: osx
      compiler: clang
      env:
        - T=amd64-macos-clang

    - arch: arm64
      os: linux
      compiler: gcc
      env:
        - T=arm64-linux-gcc
        - CFLAGS="${CFLAGS} -Wformat-signedness"

script:
  - |
    (
    set -ex
    case $T in
    *)
      ./configure || true
      cat config.log
      make test
      # Ensure assertions are free from side effects.
      env CPPFLAGS="${CPPFLAGS} -DNDEBUG" ./configure || true
      cat config.log
      make test
      ;;
    esac
    )
