.Dd $Mdocdate: March 17 2018 $
.Dt MDSORT.CONF 5
.Os
.Sh NAME
.Nm mdsort.conf
.Nd mdsort configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for
.Xr mdsort 1 .
.Pp
Comments can be put anywhere in the file using a hash mark
.Pq Sq #
and extend to the end of the current line.
.Pp
Each
.Ic maildir
section starts with a declaration of the maildir and its corresponding
.Ar path :
.Bl -tag -width Ds
.It Ic maildir Do Ar path Dc No { Ar rule ... No }
.El
.Pp
Followed by a block of rules.
.Xr mdsort 1
iterates over each message present in the
.Pa cur
and
.Pa new
directory rooted in
.Ar path
and evaluates each rule in sequential order.
The first matching rule is favored.
.Pp
A rule is defined as follows:
.Bl -tag -width XXX
.It Ic match Ar condition action
A rule starts with the
.Ic match
keyword followed by conditions then actions to perform if the conditions
evaluates to true.
Each rule spans to the end of the current line but can extended over multiple
lines using a backslash
.Pq Sq \e .
.Pp
A
.Ar pattern
used within a condition is interpreted as an extended regular expression and can
be made case insensitive using the
.Ic i
keyword.
.Pp
The conditions are as follows and may be negated:
.Bl -tag -width Ds
.It Ic all
Evaluates to true for any message.
.It Oo Ic \&! Oc Ic body No / Ns Ar pattern Ns / Ns Op Ic i
Evaluates to true if the message body matches
.Ar pattern .
.It Oo Ic \&! Oc Ic header Do Ar name Dc / Ns Ar pattern Ns / Ns Op Ic i
Evaluates to true if the value of the header with
.Ar name
in message matches
.Ar pattern .
Finding the header with
.Ar name
in message is done case insensitive.
.It Oo Ic \&! Oc Ic header No { Do Ar name Dc Ar ... No } / Ns Ar pattern Ns / Ns Op Ic i
Evaluates to true if the value of any of the headers with
.Ar name ...
in message matches
.Ar pattern .
Finding the header with
.Ar name ...
in message is done case insensitive.
.It Oo Ic \&! Oc Ic new
Evaluates to true if the message is not read.
.It Oo Ic \&! Oc Ic old
Evaluates to true if the message is old.
Meaning, a message that has been read but later flagged as not read.
.El
.Pp
Multiple and nested conditions may be also specified:
.Bl -tag -width Ds
.It Ar condition Ic and Ar condition
Evaluates to true if both
.Ar condition
are true.
.It Ar condition Ic or Ar condition
Evaluates to true if any of the
.Ar condition
are true.
.It Oo Ic \&! Oc Ic \&( Ar condition Ic \&)
Evaluates to true if the nested
.Ar condition
is true.
.El
.Pp
Next comes one or many actions:
.Bl -tag -width Ds
.It Ic flag Oo Ic \&! Oc Ic new
Flag the message as read or not.
.It Ic move Dq Ar path
Move the message to the maildir located at
.Ar path .
The
.Ar path
may contain back-references on the form
.Sq \e#
where
.Sq #
is a digit.
The digit refers to the nth subexpression of the first matching
.Ar pattern
and will be replaced with matched string.
Note, using back-references with many
.Ic or
conditions is not encouraged since the
.Ar pattern
that matches first may vary.
.Pp
Only one
.Ic move
action can be defined per rule.
.El
.It Ic match Ar condition No { Ar rule ... No }
The nested block of rules
is only evaluated if
.Ar condition
is true.
.El
.Sh FILES
.Bl -tag -width "~/.mdsort.conf"
.It Pa ~/.mdsort.conf
The default configuration file.
.El
.Sh EXAMPLES
.Bd -literal
maildir "~/Maildir/INBOX" {
	# Move messages from OpenBSD mailing lists into dedicated directories.
	match header { "Cc" "To" } /(bugs|misc|ports|tech)@openbsd.org/i \e
		move "~/Maildir/openbsd-\e1"

	# Get rid of potential spam.
	match header "Received-SPF" /fail/ or header "X-Spam-Score" /[1-9]/ \e
		move "~/Maildir/Spam"

	# Archive read messages.
	match ! new move "~/Maildir/Archive"
}
.Ed
.Sh SEE ALSO
.Xr mdsort 1 ,
.Xr re_format 7
.Sh AUTHORS
.An Anton Lindqvist Aq Mt anton@basename.se
