name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        compiler: [gcc, clang]
        mode: [asan, ubsan, musl, valgrind, bison, fuzz]
        exclude:
          - os: macos-latest
            compiler: gcc

          - mode: musl
            os: macos-latest

          - mode: musl
            os: ubuntu-22.04
            compiler: clang

          - mode: valgrind
            os: macos-latest

          - mode: valgrind
            os: ubuntu-22.04
            compiler: clang

          - mode: bison
            os: macos-latest

          - mode: bison
            os: ubuntu-22.04
            compiler: clang

          - mode: fuzz
            os: ubuntu-22.04
            compiler: clang

          - mode: fuzz
            os: macos-latest

        include:
          - os: ubuntu-22.04
            nproc: nproc

          - os: macos-latest
            nproc: sysctl -n hw.logicalcpu
            cflags: -Wno-sign-conversion

          - compiler: gcc
            cflags: -Wformat-signedness

          - mode: asan
            debug1: -fsanitize=address
            testflags: -Tmemleak

          - mode: ubsan
            debug1: -fsanitize=undefined -fno-sanitize-recover=all

          - mode: ubsan
            compiler: clang
            debug2: -fsanitize=unsigned-integer-overflow

          - mode: musl
            cc: musl-gcc
            deps_mode: musl-tools
            musl: 1
            testflags: -Ttilde

          - mode: valgrind
            deps_mode: valgrind
            exec: valgrind
            testflags: -Tmemleak
            valgrind: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all

          - mode: bison
            yacc: bison
            yflags: -y -Werror

          - mode: fuzz
            cc: afl-gcc
            deps_mode: afl

    steps:
      - uses: actions/checkout@v2

      - name: dependenices
        if: ${{matrix.deps_os || matrix.deps_mode}}
        run: sudo apt-get update && sudo apt-get install ${{matrix.deps_os}} ${{matrix.deps_mode}}

      - name: test
        env:
          ASAN_OPTIONS: exitcode=66
          CC: ${{matrix.cc || matrix.compiler}}
          CFLAGS: -Werror -Wmissing-prototypes -Wpedantic -Wsign-conversion -Wshadow -Wwrite-strings ${{matrix.cflags}}
          CPPFLAGS: ${{matrix.cppflags}}
          DEBUG: -g -O2 ${{matrix.debug1}} ${{matrix.debug2}}
          EXEC: ${{matrix.exec}}
          MODE: ${{matrix.mode}}
          MUSL: ${{matrix.musl}}
          TESTFLAGS: -Tfdleak ${{matrix.testflags}}
          VALGRIND_OPTS: ${{matrix.valgrind}}
          YACC: ${{matrix.yacc || 'yacc'}}
          YFLAGS: ${{matrix.yflags}}
        run: |
          set -ex
          ${CC} -v
          MAKE="make -j `${{matrix.nproc}}`"
          env CPPFLAGS="${CPPFLAGS} -DDIAGNOSTIC" ./configure || :
          cat config.log
          if [ "${MODE}" == "fuzz" ]; then
            ${MAKE} fuzz
            exit 0
          fi
          ${MAKE} test
          # Ensure faults and assertions are free from side effects.
          env CPPFLAGS="${CPPFLAGS} -DNDEBUG" ./configure || :
          cat config.log
          ${MAKE} test "TESTFLAGS=${TESTFLAGS} -Tfault"

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: clang-tidy
        run: |
          ./configure
          make lint-clang-tidy

  cppcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install cppcheck
      - name: cppcheck
        run: |
          ./configure
          make lint-cppcheck
