name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]
        mode: [asan, ubsan, musl, valgrind, bison]
        exclude:
          - os: macos-latest
            compiler: gcc

          - mode: musl
            os: macos-latest

          - mode: musl
            os: ubuntu-latest
            compiler: clang

          - mode: valgrind
            os: macos-latest

          - mode: valgrind
            os: ubuntu-latest
            compiler: clang

          - mode: bison
            os: macos-latest

          - mode: bison
            os: ubuntu-latest
            compiler: clang

        include:
          - os: ubuntu-latest
            nproc: nproc

          - os: macos-latest
            nproc: sysctl -n hw.logicalcpu

          - compiler: gcc
            cflags: -Wformat-signedness

          - mode: asan
            debug1: -fsanitize=address
            testflags: -Tmemleak

          - mode: ubsan
            debug1: -fsanitize=undefined -fno-sanitize-recover=all

          - mode: ubsan
            compiler: clang
            debug2: -fsanitize=unsigned-integer-overflow

          - mode: musl
            cc: musl-gcc
            dependenices: musl-tools
            musl: 1
            testflags: -Ttilde

          - mode: valgrind
            dependenices: valgrind
            exec: valgrind
            testflags: -Tmemleak
            valgrind: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all

          - mode: bison
            yacc: bison
            yflags: -y -Werror

    steps:
      - uses: actions/checkout@v2

      - name: dependenices
        if: ${{matrix.dependenices}}
        run: sudo apt-get update && sudo apt-get install ${{matrix.dependenices}}

      - name: test
        env:
          ASAN_OPTIONS: exitcode=66
          CC: ${{matrix.cc || matrix.compiler}}
          CFLAGS: -Werror -Wpedantic -Wshadow ${{matrix.cflags}}
          CPPFLAGS: ${{matrix.cppflags}}
          DEBUG: -g -O2 ${{matrix.debug1}} ${{matrix.debug2}}
          EXEC: ${{matrix.exec}}
          MUSL: ${{matrix.musl}}
          TESTFLAGS: -Tfdleak ${{matrix.testflags}}
          VALGRIND_OPTS: ${{matrix.valgrind}}
          YACC: ${{matrix.yacc || 'yacc'}}
          YFLAGS: ${{matrix.yflags}}
        run: |
          set -ex
          ${CC} -v
          MAKE="make -j `${{matrix.nproc}}`"
          env CPPFLAGS="${CPPFLAGS} -DDIAGNOSTIC" ./configure || :
          cat config.log
          ${MAKE} test
          # Ensure faults and assertions are free from side effects.
          env CPPFLAGS="${CPPFLAGS} -DNDEBUG" ./configure || :
          cat config.log
          ${MAKE} test "TESTFLAGS=${TESTFLAGS} -Tfault"
