name: test

on:
  - push
  - pull_request

jobs:
  linux-clang-sanitize-address:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic --sanitize address
          make -j`nproc` test

  linux-clang-sanitize-memory:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic --sanitize memory
          make -j`nproc` test

  linux-gcc-bison:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak
          YACC: bison
          YFLAGS: -y -Werror
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-gcc-i386:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install gcc-multilib
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          CFLAGS: -m32
          LDFLAGS: -m32
          TESTFLAGS: -Tfdleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-gcc-musl:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install musl-tools
      - name: test
        env:
          CC: musl-gcc
          CPPFLAGS: -DDIAGNOSTIC
          MUSL: 1
          TESTFLAGS: -Tfdleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-gcc-ndebug:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC -DNDEBUG
          TESTFLAGS: -Tfdleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-gcc-sanitize-address:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic --sanitize address
          make -j`nproc` test

  linux-gcc-valgrind:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install valgrind
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          EXEC: valgrind
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  macos-clang-sanitize-address:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          # yacc does not emit sign-conversion conformant code.
          ./configure --sanitize address
          make -j`sysctl -n hw.logicalcpu` test
