name: test

on:
  - push
  - pull_request

jobs:
  linux-gcc-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          DEBUG: -fsanitize=address,undefined -fno-sanitize-recover=all
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  linux-clang-sanitize:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          CPPFLAGS: -DDIAGNOSTIC
          DEBUG: -fsanitize=address,undefined,unsigned-integer-overflow -fno-sanitize-recover=all
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  macos-clang-sanitize:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: clang
          CPPFLAGS: -DDIAGNOSTIC
          DEBUG: -fsanitize=address,undefined,unsigned-integer-overflow -fno-sanitize-recover=all
          TESTFLAGS: -Tfdleak -Tmemleak
        run: |
          # yacc does not emit sign-conversion conformant code.
          ./configure
          make -j`sysctl -n hw.logicalcpu` test

  valgrind:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install valgrind
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          EXEC: valgrind
          TESTFLAGS: -Tfdleak -Tmemleak
          VALGRIND_OPTS: --quiet --error-exitcode=1 --leak-check=full --errors-for-leak-kinds=all --show-leak-kinds=all
        run: |
          ./configure --pedantic
          make -j`nproc` test

  musl:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install musl-tools
      - name: test
        env:
          CC: musl-gcc
          CPPFLAGS: -DDIAGNOSTIC
          MUSL: 1
          TESTFLAGS: -Tfdleak -Ttilde
        run: |
          ./configure --pedantic
          make -j`nproc` test

  bison:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC
          TESTFLAGS: -Tfdleak -Ttilde
          YACC: bison
          YFLAGS: -y -Werror
        run: |
          ./configure --pedantic
          make -j`nproc` test

  ndebug:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        env:
          CC: gcc
          CPPFLAGS: -DDIAGNOSTIC -DNDEBUG
          TESTFLAGS: -Tfdleak
        run: |
          ./configure --pedantic
          make -j`nproc` test

  fuzz:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install afl
      - name: test
        env:
          CC: afl-gcc
        run: |
          ./configure --pedantic
          make -j`nproc` fuzz

  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clang-tidy
        run: |
          ./configure --pedantic
          make lint-clang-tidy

  cppcheck:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dependenices
        run: sudo apt-get update && sudo apt-get install cppcheck
      - name: cppcheck
        run: |
          ./configure --pedantic
          make lint-cppcheck
